<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
            'name' => 'Milo Machiato',
            'description' => 'waaa',
            'image' => 'storage/products/1.jpg',
            'price' => 23000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Lychee Yakult',
            'description' => 'waaa',
            'image' => 'storage/products/2.jpg',
            'price' => 18000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Kopi Susu',
            'description' => 'waaa',
            'image' => 'storage/products/3.jpg',
            'price' => 10000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Soklat Berry',
            'description' => 'waaa',
            'image' => 'storage/products/4.jpg',
            'price' => 28000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Matcha Machiato',
            'description' => 'waaa',
            'image' => 'storage/products/5.jpg',
            'price' => 10000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Caramel Latte',
            'description' => 'waaa',
            'image' => 'storage/products/6.jpg',
            'price' => 15000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Susu Cincau',
            'description' => 'waaa',
            'image' => 'storage/products/7.jpg',
            'price' => 20000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Cookies and Cream',
            'description' => 'waaa',
            'image' => 'storage/products/8.jpg',
            'price' => 15000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Teh Cincau Pandan',
            'description' => 'waaa',
            'image' => 'storage/products/9.jpg',
            'price' => 17000,
            'stock' => 50,
            'category_id' => 5,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Char Siu Pork',
            'description' => 'waaa',
            'image' => 'storage/products/10.jpg',
            'price' => 48000,
            'stock' => 50,
            'category_id' => 1,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Kungpao Chicken',
            'description' => 'waaa',
            'image' => 'storage/products/11.jpg',
            'price' => 32000,
            'stock' => 50,
            'category_id' => 1,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Hot Pot',
            'description' => 'waaa',
            'image' => 'storage/products/12.jpg',
            'price' => 80000,
            'stock' => 50,
            'category_id' => 1,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Mapo Tofu',
            'description' => 'waaa',
            'image' => 'storage/products/13.jpg',
            'price' => 23000,
            'stock' => 50,
            'category_id' => 1,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Sushi',
            'description' => 'waaa',
            'image' => 'storage/products/14.jpg',
            'price' => 19000,
            'stock' => 50,
            'category_id' => 2,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Ramen',
            'description' => 'waaa',
            'image' => 'storage/products/15.jpe',
            'price' => 45000,
            'stock' => 50,
            'category_id' => 2,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Dango',
            'description' => 'waaa',
            'image' => 'storage/products/16.jpeg',
            'price' => 10000,
            'stock' => 50,
            'category_id' => 2,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Takoyaki',
            'description' => 'waaa',
            'image' => 'storage/products/17.webp',
            'price' => 15000,
            'stock' => 50,
            'category_id' => 2,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Sashimi',
            'description' => 'waaa',
            'image' => 'storage/products/18.jpg',
            'price' => 50000,
            'stock' => 50,
            'category_id' => 2,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Spaghetti Bolognaise',
            'description' => 'waaa',
            'image' => 'storage/products/19.jpg',
            'price' => 32000,
            'stock' => 50,
            'category_id' => 4,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Pizza',
            'description' => 'waaa',
            'image' => 'storage/products/20.webp',
            'price' => 65000,
            'stock' => 50,
            'category_id' => 4,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Spaghetti Carbonara',
            'description' => 'waaa',
            'image' => 'storage/products/21.jpeg',
            'price' => 34000,
            'stock' => 50,
            'category_id' => 4,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Risotto',
            'description' => 'waaa',
            'image' => 'storage/products/22.webp',
            'price' => 14000,
            'stock' => 50,
            'category_id' => 4,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Ravioli',
            'description' => 'waaa',
            'image' => 'storage/products/23.jpg',
            'price' => 36000,
            'stock' => 50,
            'category_id' => 4,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Chicken Cordon Bleu',
            'description' => 'waaa',
            'image' => 'storage/products/24.jpg',
            'price' => 42000,
            'stock' => 50,
            'category_id' => 3,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Fish and Chips',
            'description' => 'waaa',
            'image' => 'storage/products/25.jpg',
            'price' => 31000,
            'stock' => 50,
            'category_id' => 3,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Berry Pancake',
            'description' => 'waaa',
            'image' => 'storage/products/26.webp',
            'price' => 29000,
            'stock' => 50,
            'category_id' => 3,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Ratatouille',
            'description' => 'waaa',
            'image' => 'storage/products/27.jpg',
            'price' => 30000,
            'stock' => 50,
            'category_id' => 3,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Tenderloin Steak',
            'description' => 'waaa',
            'image' => 'storage/products/28.webp',
            'price' => 75000,
            'stock' => 50,
            'category_id' => 3,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Burger',
            'description' => 'waaa',
            'image' => 'storage/products/29.jpg',
            'price' => 24000,
            'stock' => 50,
            'category_id' => 3,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
            [
            'name' => 'Beef Lasagna',
            'description' => 'waaa',
            'image' => 'storage/products/30.jpeg',
            'price' => 30000,
            'stock' => 50,
            'category_id' => 3,
            'is_available' => 1,
            'is_favorite' => 1,
            ],
        ];

        foreach($products as $product){
            Product::create($product);
        }
    }
}
